INSERT INTO website.tb_blindbox_event
(id, event_name, event_endpoint, event_description, detail, avatar_img_url, background_img_url, roadmap_description, roadmap_list, website_url, whitepaper_url, twitter_url, discord_url, price_sats, is_active, is_display, payment_token, current_mint_plan_index, mint_plan_list, img_url_list, average_image_bytes, supply, avail, lock_count, mint_limit, only_whitelist, start_time, end_time, create_time, update_time)
VALUES(1, 'Azuki', 'azuki', 'Azuki is Azuki', 'Azuki Azuki Azuki Azuki Azuki Azuki Azuki Azuki Azuki Azuki Azuki Azuki Azuki Azuki Azuki Azuki Azuki Azuki Azuki Azuki', 'https://azk.imgix.net/images/166a4190-1377-4cc2-9b93-e1cd32a72ac1.png', 'https://azk.imgix.net/images/166a4190-1377-4cc2-9b93-e1cd32a72ac1.png', 'this is roadmap description this is roadmap description this is roadmap description  this is roadmap description ', 'freemint;vip sale;auction sale;public sale', 'https://www.azuki.com/zh', 'https://www.azuki.com/zh', 'https://twitter.com/Azuki', 'http://discord.gg/azuki', 1000, 1, 1, 'BTC', 0, 'Freemint,June 29 at 11:00 PM UTC+0;Public Sale,2023-07-11 20:00 UTC+0', 'https://azk.imgix.net/images/166a4190-1377-4cc2-9b93-e1cd32a72ac1.png;https://azk.imgix.net/images/57451d86-b9d2-4199-a91f-fcdfba68d2cf.png;https://azk.imgix.net/images/57451d86-b9d2-4199-a91f-fcdfba68d2cf.png;https://azk.imgix.net/images/57451d86-b9d2-4199-a91f-fcdfba68d2cf.png', 550, 2000, 1996, 0, 10, 0, '2023-07-03 17:28:59', '2023-08-03 17:28:59', '2023-07-03 17:28:59', '2023-07-12 11:11:50');
INSERT INTO website.tb_blindbox_event
(id, event_name, event_endpoint, event_description, detail, avatar_img_url, background_img_url, roadmap_description, roadmap_list, website_url, whitepaper_url, twitter_url, discord_url, price_sats, is_active, is_display, payment_token, current_mint_plan_index, mint_plan_list, img_url_list, average_image_bytes, supply, avail, lock_count, mint_limit, only_whitelist, start_time, end_time, create_time, update_time)
VALUES(2, 'Punks', 'cryptopunks', 'Punks is CryptoPunks', 'Punks Punks Punks Punks Punks Punks Punks Punks Punks Punks Punks Punks Punks Punks Punks Punks Punks Punks Punks Punks', 'https://bitcoinpunks.com/punks-bg/punk0070.png', 'https://bitcoinpunks.com/punks-bg/punk9085.png', 'this is roadmap of Crypto Punks', 'freemint;vip sale;auction sale;public sale', 'https://cryptopunks.app/', 'https://cryptopunks.app/', 'https://twitter.com/cryptopunksnfts', 'https://t.co/zFvNWfBy6C', 1024, 1, 1, 'BTC', 0, 'Freemint,June 29 at 11:00 PM UTC+0;Public Sale,2023-07-11 20:00 UTC+0', 'https://bitcoinpunks.com/punks-bg/punk9085.png;https://bitcoinpunks.com/punks-bg/punk0070.png;https://bitcoinpunks.com/punks-bg/punk7223.png;https://bitcoinpunks.com/punks-bg/punk0482.png', 550, 3, 3, 0, 1, 0, '2023-07-03 17:43:29', '2023-09-03 17:43:29', '2023-07-03 17:43:29', '2023-07-12 11:12:03');
INSERT INTO website.tb_blindbox_event
(id, event_name, event_endpoint, event_description, detail, avatar_img_url, background_img_url, roadmap_description, roadmap_list, website_url, whitepaper_url, twitter_url, discord_url, price_sats, is_active, is_display, payment_token, current_mint_plan_index, mint_plan_list, img_url_list, average_image_bytes, supply, avail, lock_count, mint_limit, only_whitelist, start_time, end_time, create_time, update_time)
VALUES(3, 'Bit Eagle', 'biteagle', 'BitEagle is a web3 brand that champions personal dreams and the pursuit of those dreams
let''s embody and spread this ideology, co-creating web3 art and culture.', 'BitEagle is a web3 brand that champions personal dreams and the pursuit of those dreams. In the world of web3, everyone is a warrior chasing freedom and their dreams. They embody strength, sharpness, resilience, and a fighting spirit. They have the determination to transform themselves and the ability to continually rebuild their strength. They work diligently like ants, staying grounded and holding onto eagle-like dreams, with a farsighted perspective that overlooks the sky.\\nBitEagle is a collection of 10,240 BTC Ordinals NFTs, where the iconic eagle symbol merges with the pixel art culture of CryptoPunks. Each artwork is unique, and stored on the Bitcoin blockchain permanently.
Own one BitEagle! Join the community of collectors, art enthusiasts, and believers in the crypto culture. Together, let''s embody and spread this ideology, co-creating web3 art and culture. Eagle is with you!\\nBitEagle is a collection of 10,240 BTC Ordinals NFTs. We have designed unique fundamental attribute features for each character, including backgrounds, bodies, mouths, eyes, clothing, neck decorations, eye decorations, mouth decorations, and head decorations. We carefully selected 10,000 pieces from over 47 million creations generated based on 140 base elements, ensuring that each NFT held by owners is truly one-of-a-kind. Additionally, there are 240 custom Elite Eagles, paying homage to the great builders, creators, and cultural symbols.', 'https://d30f95b5opmmez.cloudfront.net/images/53.png', 'https://d30f95b5opmmez.cloudfront.net/images/215.png', 'roadmap', 'BitEagles Eggs Distributed;BitEagle Mint;Marketplace launching;Special Gift;Token Plan Lauching;Brand Development', 'https://www.biteagle.io/', 'https://www.biteagle.io/', 'https://twitter.com/biteagle10240', 'https://twitter.com/biteagle10240', 0, 1, 1, 'BTC', 0, 'Freemint, 2023-06-28 14:00 UTC+0; Public Sale,2023-07-29 14:00 UTC+0', 'https://d30f95b5opmmez.cloudfront.net/images/1.png;https://d30f95b5opmmez.cloudfront.net/images/871.png;https://d30f95b5opmmez.cloudfront.net/images/969.png;https://d30f95b5opmmez.cloudfront.net/images/143.png', 550, 1000, 0, 0, 1, 0, '2023-07-06 20:29:39', '2023-07-06 20:29:39', '2023-07-06 20:29:39', '2023-07-12 11:11:50');
