// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	joinwaitlist "github.com/fantopia-dev/website/internal/handler/joinwaitlist"
	"github.com/fantopia-dev/website/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/joinwaitlist",
				Handler: joinwaitlist.JoinWaitListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
